INSERT INTO DEVICE VALUES(1, 'system name 1', 0);
INSERT INTO DEVICE VALUES(2, 'system name 2', 2);

--INSERT INTO JOB_SERVICE VALUES(1, 'Antivirus', 5.0);
--INSERT INTO JOB_SERVICE VALUES(2, 'Backup', 3.0);
